config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('todo.urls')),
]

todo/urls.py
from django.urls import path

from . import views

app_name = 'todo'

urlpatterns = [ 
    path('',views.index,name='index'),
    path('make_goal',views.make_goal,name='make_goal'),
    path('read_more/<int:fir>',views.read_more,name='read_more'),
    path('suc_gl/<int:fir>',views.suc_gl,name='suc_gl'),
]

todo/models.py
from django.db import models


class goal(models.Model):
    subject = models.CharField(max_length=100)
    content = models.TextField()
    create_date = models.CharField(max_length=30)
    end_date = models.CharField(max_length=30)
    

class cle_gl(models.Model):
    subject = models.CharField(max_length=100)    
    cre_date = models.CharField(max_length=30)
    end_date = models.CharField(max_length=30)
    
# Create your models here.

todo/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import goal,cle_gl
from django.core.paginator import Paginator
import datetime
def index(request):
    page = int(request.GET.get('page',0))
    if page>=1 :
        page= page-1
    goal_=goal.objects.all()
    finish_=cle_gl.objects.all()[page*10:page*10+10] 
    return render(request,'index.html',{'goal_':goal_,'finish_':finish_})

def make_goal(request):
    
    if request.method == 'POST':
        subject=request.POST.get('subject')
        content=request.POST.get('content')
        end_date=request.POST.get('end_date')
        now=datetime.datetime.now()
        create_date=str(now)[:10]
        print(end_date)
        print(create_date)
        q=goal(subject=subject,content=content,create_date=create_date,end_date=end_date)
        q.save()
        return redirect('todo:index')
    return render(request,'make_goal.html')

def read_more(request,fir):
    if request.method == 'POST':
        q=get_object_or_404(goal,pk=fir)
        q.subject=request.POST.get('subject')
        q.content=request.POST.get('content')
        q.end_date=request.POST.get('end_date')
        q.save()
        return redirect('todo:index')
    return render(request,'edit_goal.html',{'val':get_object_or_404(goal,pk=fir)})

def suc_gl(request,fir):
    if request.method=='GET':
        cg=cle_gl()
        q=get_object_or_404(goal,pk=fir)
        cg.subject=q.subject
        cg.cre_date=q.create_date
        cg.end_date=str(datetime.datetime.now())[:10]
        cg.save()
        q.delete()
        return redirect('todo:index')

templates/base.html
{% load static %}
<html>
  <head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">
    <!-- <link rel="stylesheet" href="{% static 'index_css.css' %}"> -->
    <!-- <link rel="stylesheet" href="{% static 'make_goal.css' %}"> -->
    {% block style %}
    {% endblock %}
  </head>
  <body>
    {% block content %}
    {% endblock %}
  </body>
</html>

templates/edit_goal.html
{% extends 'base.html' %}
{% block style %}
<link rel="stylesheet" href="/static/make_goal.css">
{% endblock %}
{% block content %}
<form class="form_main" method="POST" action="">
	{% csrf_token %}
      <div class="form-group">
	      <input type="text" class="form-control" name="subject" placeholder="목표 입력" 
							      value="{{ val.subject }}">
      </div>
      <div class="form-group">
        <textarea class="sub_main" name="content"
				   placeholder="부가 설명">{{ val.content }}</textarea>
      </div>
       <div class="form-group" style="width:220px">
         <label for="" >목표 일자</label>
	 <input type="date" name="end_date" value="{{ val.end_date }}">
       </div>
      <button type="submit" class="subtton btn btn-primary">확인</button>
    </form>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block style %}
<link rel="stylesheet" href="/static/index_css.css">
{% endblock %}
{% block content %}
 <div class="main_board">
    <div class="main_title">
      목표 리스트!
    </div>
    <div class="sub_board">
      <div class="finish_goal_list">
          {% if finish_ %}
          {% for finish_item in finish_ %}
          
          <div class="finish_goal_item">
            {{ finish_item.subject }}
          <div class="all_date">
            {{ finish_item.cre_date }}-{{ finish_item.end_date }}
            </div>
          </div>
          
          {% endfor %}
          {% endif %}
        
        <nav aria-label="Page navigation example">
          <ul class="finish_page pagination">
            <li class="page-item"><a class="page-link" href="/?page=1">1</a></li>
            <li class="page-item"><a class="page-link" href="/?page=2">2</a></li>
            <li class="page-item"><a class="page-link" href="/?page=3">3</a></li>
            
          </ul>
        </nav>
      </div>
      
      <div class="make_goal_list">
          {% if goal_ %}
          {% for goal_item in goal_ %}
     <div class="goal_item">
      <div class="goal_">
          {{ goal_item.subject }}
          </div>
          <a class="btn btn-success" style="margin-left:10px;" href="{% url 'todo:suc_gl' goal_item.id %}">
            성공!
          </a>
          <a class="btn btn-primary" style="margin-left:10px;" href="{% url 'todo:read_more' goal_item.id %}">
                  상세보기(수정)
          </a>

        </div>
        {% endfor %}
        {% endif %}
        <a href="{% url 'todo:make_goal' %}" class="btn btn-primary add_item_goal">
        목표 만들기
        </a>
      </div>
    </div>
  </div>
{% endblock %}

templates/make_goal.html
{% extends 'base.html' %}
{% block style %}
<link rel="stylesheet" href="/static/make_goal.css">
{% endblock %}
{% block content %}
	<form class="form_main" method="POST" action="">
        {% csrf_token %}
        <div class="form-group">
            <input type="text" class="form-control" name="subject" placeholder="목표 입력">
        </div>
        <div class="form-group">
            <textarea class="sub_main" name="content" placeholder="부가 설명"></textarea>
        </div>
        <div class="form-group" style="width:220px">
            <label for="">목표 일자</label>
            <input type="date" name="end_date">
        </div>
        <a href="/" class="btn btn-primary" style="position:absolute;bottom:50px;width:100px;height:50px;">back</a>
        <button type="submit" class="subtton btn btn-primary">Submit</button>
    </form>
{% endblock %}